/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class client_JNIPlayer */

#ifndef _Included_client_JNIPlayer
#define _Included_client_JNIPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     client_JNIPlayer
 * Method:    newxskatplayer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_client_JNIPlayer_newxskatplayer
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     client_JNIPlayer
 * Method:    newjniplayer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_client_JNIPlayer_newjniplayer
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     client_JNIPlayer
 * Method:    newskattaplayer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_client_JNIPlayer_newskattaplayer
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     client_JNIPlayer
 * Method:    deletePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_client_JNIPlayer_deletePlayer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     client_JNIPlayer
 * Method:    computeMove
 * Signature: (JLjava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_client_JNIPlayer_computeMove
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     client_JNIPlayer
 * Method:    gameChange
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_client_JNIPlayer_gameChange
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     client_JNIPlayer
 * Method:    interruptMoveComputation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_client_JNIPlayer_interruptMoveComputation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     client_JNIPlayer
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_client_JNIPlayer_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     client_JNIPlayer
 * Method:    DDS
 * Signature: (JIIIIIIIIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_client_JNIPlayer_DDS
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     client_JNIPlayer
 * Method:    paranoid_init
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_client_JNIPlayer_paranoid_1init
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     client_JNIPlayer
 * Method:    paranoid
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_client_JNIPlayer_paranoid
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     client_JNIPlayer
 * Method:    w_paranoid
 * Signature: (JIIIIIIIIIIIII[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_client_JNIPlayer_w_1paranoid
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
